# Generated by Django 5.2.5 on 2026-04-10 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_add_piper_tts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='job_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_project_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='segment',
            name='segment_job_index_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch'), ('it', 'Italiano'), ('pt', 'Português')], default='fr', max_length=5, verbose_name='langue'),
        ),
        migrations.AlterField(
            model_name='job',
            name='stt_engine',
            field=models.CharField(choices=[('faster_whisper', 'Faster-Whisper (recommandé)')], default='faster_whisper', max_length=20, verbose_name='moteur STT'),
        ),
        migrations.AlterField(
            model_name='job',
            name='thumbnail_paths',
            field=models.JSONField(blank=True, default=list, verbose_name='vignettes'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tts_engine',
            field=models.CharField(choices=[('elevenlabs', 'ElevenLabs (premium)'), ('cartesia', 'Cartesia Sonic (ultra-rapide)')], default='elevenlabs', max_length=20, verbose_name='moteur TTS'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tts_voice',
            field=models.CharField(default='narrateur_pro', max_length=100, verbose_name='voix TTS'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='video_filename',
            field=models.CharField(blank=True, help_text="Nom original affiché dans l'interface", max_length=255, verbose_name='nom original'),
        ),
        migrations.AlterField(
            model_name='job',
            name='waveform_data',
            field=models.JSONField(blank=True, default=list, verbose_name='waveform'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='audio_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='fichier audio TTS'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='studio.job'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='text',
            field=models.TextField(verbose_name='texte original'),
        ),
    ]
