# Generated by Django 5.2.5 on 2026-04-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_remove_job_job_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, help_text="Titre saisi par l'utilisateur dans l'interface", max_length=255, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='job',
            name='video_filename',
            field=models.CharField(blank=True, help_text="Nom exact du fichier uploadé par l'utilisateur", max_length=255, verbose_name='nom original du fichier'),
        ),
    ]
