# Generated by Django 5.2.5 on 2026-04-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_job_title_alter_job_video_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='actual_tts_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='durée TTS réelle (ms)'),
        ),
        migrations.AddField(
            model_name='segment',
            name='speed_factor',
            field=models.FloatField(default=1.0, help_text='< 1.0 = ralenti, > 1.0 = accéléré, 1.0 = normal', verbose_name='facteur vitesse vidéo'),
        ),
        migrations.AddField(
            model_name='segment',
            name='speed_forced',
            field=models.BooleanField(default=False, help_text='Si True, on ne recalcule pas automatiquement', verbose_name="vitesse forcée par l'user"),
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(max_length=100, verbose_name='identifiant voix')),
                ('tts_engine', models.CharField(choices=[('elevenlabs', 'ElevenLabs'), ('cartesia', 'Cartesia')], max_length=20, verbose_name='moteur TTS')),
                ('wpm_default', models.FloatField(default=145.0, verbose_name='WPM par défaut')),
                ('wpm_measured', models.FloatField(blank=True, null=True, verbose_name='WPM mesuré réel')),
                ('nb_samples', models.PositiveIntegerField(default=0, verbose_name='nombre de mesures')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'profil voix',
                'verbose_name_plural': 'profils voix',
                'unique_together': {('voice_id', 'tts_engine')},
            },
        ),
    ]
