# Generated by Django 5.2.5 on 2026-04-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_segment_actual_tts_ms_segment_speed_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='trim_end_ms',
            field=models.IntegerField(default=0, help_text='Point OUT dans la vidéo source (ms). 0 = utiliser end_ms'),
        ),
        migrations.AddField(
            model_name='segment',
            name='trim_start_ms',
            field=models.IntegerField(default=0, help_text='Point IN dans la vidéo source (ms)'),
        ),
    ]
