# Generated by Django 5.2.5 on 2026-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_segment_trim_end_ms_segment_trim_start_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='subtitled_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL vidéo sous-titrée'),
        ),
    ]
