# Generated by Django 5.2.5 on 2026-05-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_job_subtitled_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Segment marqué supprimé par l'utilisateur — exclu de l'assemblage", verbose_name='supprimé'),
        ),
    ]
