# Generated by Django 5.2.5 on 2026-05-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_segment_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('desc', models.TextField(verbose_name='description')),
                ('cat', models.CharField(choices=[('presentation', 'Présentation'), ('compte', 'Mon compte'), ('securite', 'Sécurité'), ('fournisseur', 'Fournisseurs')], max_length=32, verbose_name='catégorie')),
                ('lv', models.CharField(choices=[('d', 'Débutant'), ('i', 'Intermédiaire'), ('a', 'Avancé')], default='d', max_length=4, verbose_name='niveau')),
                ('src', models.URLField(max_length=1024, verbose_name='URL vidéo')),
                ('img', models.URLField(blank=True, max_length=1024, verbose_name='URL miniature')),
                ('tags', models.JSONField(default=list, verbose_name='tags')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tutoriel',
                'verbose_name_plural': 'tutoriels',
                'ordering': ['order', 'id'],
            },
        ),
    ]
