# Generated by Django 5.2.5 on 2026-05-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='downloads',
            field=models.JSONField(blank=True, default=list, verbose_name='téléchargements'),
        ),
    ]
